-- local mason_ok, mason = pcall(require, "mason")
-- local mason_lspconfig_ok, mason_lspconfig = pcall(require, "mason")
-- if not mason_ok or not mason_lspconfig_ok then
--   print("Mason cannot be loaded.")
--   return
-- end
-- 
-- mason.setup()
-- 
-- local default_setup = function(server)
--   require("lspconfig")[server].setup({})
-- end
-- 
-- mason_lspconfig.setup({
--   ensure_installed = {},
--   handlers = {
--     default_setup,
--     lua_ls = function()
--       require('lspconfig').lua_ls.setup({
--         settings = {
--           Lua = {
--             runtime = {
--               version = 'LuaJIT'
--             },
--             diagnostics = {
--               globals = {'vim'},
--             },
--             workspace = {
--               library = {
--                 vim.env.VIMRUNTIME,
--               }
--             }
--           }
--         }
--       })
--     end,
--   },
-- })
